# vim:fileencoding=utf-8:ft=conf:foldmethod=marker:foldlevel=0

#: Fonts {{{

font_family      Cartograph CF
bold_font        Cartograph CF
italic_font      Cartograph CF
bold_italic_font Cartograph CF

font_size 16.0

symbol_map U+f101-U+f25c nonicons

}}}


#: History {{{ 

scrollback_lines 20000

#}}}


#: Mouse {{{ 

focus_follows_mouse yes

#}}}


#: Window {{{ 

enabled_layouts Splits,Stack

draw_minimal_borders yes
inactive_text_alpha 0.8
hide_window_decorations yes

window_border_width 0
window_margin_width 0
single_window_margin_width 0
window_padding_width 20

placement_strategy top-left


tab_bar_style separator


}}}


#: OS {{{ 

macos_show_window_title_in none
macos_titlebar_color background

}}


#: Theme {{{ 

include theme/nordic.conf

#}}}
