# vim:fileencoding=utf-8:ft=conf:foldmethod=marker:foldlevel=0

#: Fonts {{{

font_family      JetBrainsMono Nerd Font Regular
bold_font        JetBrainsMono Font Bold
italic_font      JetBrainsMono Font Italic
bold_italic_font JetBrainsMono Font Bold Italic	

font_size 15.0

adjust_line_height  150%
modify_font strikethrough_position 16px
symbol_map U+f101-U+f25c nonicons

#: }}}


#: History {{{ 

scrollback_lines 20000

#}}}


#: Mouse {{{ 

focus_follows_mouse yes

#}}}


#: Window {{{ 

enabled_layouts Splits,Stack

draw_minimal_borders yes
inactive_text_alpha 0.8
hide_window_decorations yes
window_padding_width 10

#}}}


#: OS {{{ 

macos_show_window_title_in none
macos_titlebar_color background
macos_thicken_font 0.75
}}}


#: Theme {{{ 

include theme/palenight.conf

#}}}
