---@class Icons
---@field icons table<string, string> General icons used throughout the configuration.
---@field kind_icons table<string, string> Icons representing different LSP kind types.

return {
  ---@type table<string, string>
  icons = {
    branch = '', --- TX-02
    bullet = '•', --- TX-02
    open_bullet = '○',
    ok = '✔',
    d_chev = '∨',
    ellipses = '…', --- TX-02
    node = '╼',
    document = '≡',
    lock = '', --- TX-02
    right_chevron = '>', -- TX-02
    left_chevron = '<', -- TX-02
    warning = ' ',
    error = ' ',
    info = ' ',
  },
  ---@type table<string, {string, string}>
  statusline_icons = {
    branch = { 'DiagnosticOk', '' },
    file = { 'NonText', '' },
    fileinfo = { 'DiagnosticInfo', '' },
    modified = { 'DiagnosticError', '•' },
    nomodifiable = { 'DiagnosticWarn', '•' },
    readonly = { 'DiagnosticWarn', '' },
    error = { 'DiagnosticError', ' ' },
    warn = { 'DiagnosticWarn', ' ' },
    visual = { 'DiagnosticInfo', '‹› ' },
  },
  ---@type table<string, string>
  kind_icons = {
    Array = ' [] ',
    BlockMappingPair = ' {} ',
    Boolean = '   ',
    BreakStatement = ' 󰙧  ',
    Call = ' ↗ ', --- TX-02
    CaseStatement = ' 󱃙  ',
    Class = '   ',
    Color = '   ',
    Constant = '   ',
    Constructor = ' 󰆦  ',
    ContinueStatement = ' → ',
    Copilot = '   ',
    Declaration = ' 󰙠  ',
    Delete = ' 󰩺 ',
    DoStatement = ' 󰑖 ',
    Element = ' {} ',
    Enum = '  ',
    EnumMember = '  ',
    Event = ' ',
    Field = '   ',
    File = '  ',
    Folder = '  ',
    ForStatement = '󰑖 ',
    Function = ' 󰆦  ',
    GotoStatement = ' → ', --- TX-02
    Identifier = ' 󰀫 ',
    IfStatement = ' 󰇉  ',
    Interface = '   ',
    Keyword = '   ',
    List = ' 󰅪 ',
    Log = ' 󰦪 ',
    Lsp = '   ',
    Macro = ' 󰁌  ',
    MarkdownH1 = ' 󰉫 ',
    MarkdownH2 = ' 󰉬 ',
    MarkdownH3 = ' 󰉭 ',
    MarkdownH4 = ' 󰉮 ',
    MarkdownH5 = ' 󰉯 ',
    MarkdownH6 = ' 󰉰 ',
    Method = ' 󰆦  ',
    Module = '   ',
    Namespace = ' {} ',
    Null = ' 󰢤  ',
    Number = ' 󰎠  ',
    Object = ' {} ',
    Operator = '   ',
    Package = ' 󰆦  ',
    Pair = ' 󰅪 ',
    Property = '   ',
    Reference = '   ',
    Regex = '  ',
    Repeat = ' 󰑖 ',
    Return = ' 󰌑  ',
    RuleSet = ' {} ',
    Scope = ' {} ',
    Section = ' {} ',
    Snippet = '   ',
    Specifier = ' 󰦪 ',
    Statement = ' {} ',
    String = '   ',
    Struct = '   ',
    SwitchStatement = '󰺟  ',
    Table = ' {} ',
    Terminal = '  ',
    Text = '   ',
    Type = '  ',
    TypeParameter = '   ',
    Unit = '  ',
    Value = '   ',
    Variable = '   ',
    WhileStatement = ' 󰑖  ',
  },
}
